### ISSUE TITLE
No colors

### ISSUE THREAD

**Issue by yonatan** [keim/SolidML#1]
Should saturation be 1 instead of 0 here?
https://github.com/keim/SolidML/blob/1ff2387fda01f053099efd872eb13024ffd9f75e/src/SolidML.js#L192

**Comment by yonatan** [comment]
The issue title could be better. Colors can be set with color or cp, but when they get multiplied saturation goes down to 0. For example this color cube from http://structuresynth.sourceforge.net/learn.php

```10 * { x 1 hue 36 } 10 * { y 1 sat 0.9 } 10 * { z 1 b 0.9 } box```

**Comment by keim** [comment]
You are right. I have modified it. Thank you.
https://github.com/keim/SolidML/blob/c8886b6f8814ff9156ebf58892b405c7e7b1dd65/src/SolidML.js#L373
